-- HOUSEKEEPING WEEK QUIZ — SUPABASE SETUP
-- Run this in Supabase SQL Editor.

create table if not exists public.quiz_scores (
  id bigint generated by default as identity primary key,
  name text not null,
  score integer not null check (score >= 0 and score <= 12),
  total integer not null default 12 check (total = 12),
  percentage integer not null check (percentage >= 0 and percentage <= 100),
  created_at timestamptz not null default now()
);

alter table public.quiz_scores enable row level security;

drop policy if exists "public can submit quiz scores" on public.quiz_scores;
create policy "public can submit quiz scores"
on public.quiz_scores
for insert
to anon
with check (
  char_length(trim(name)) between 1 and 40
  and score between 0 and 12
  and total = 12
  and percentage between 0 and 100
);

drop policy if exists "public can view leaderboard" on public.quiz_scores;
create policy "public can view leaderboard"
on public.quiz_scores
for select
to anon
using (true);

-- Optional: expose the table through Supabase Data API.
-- In the Supabase dashboard, make sure quiz_scores is included in the
-- exposed public schema/Data API settings if your project requires it.
